# Generated by Django 3.0.4 on 2020-04-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('slug', models.CharField(max_length=255, verbose_name='نامک')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('track_id', models.CharField(max_length=64, verbose_name='کد پیگیری')),
                ('status', models.CharField(choices=[('waiting', 'در انتظار'), ('checking', 'درحال بررسی'), ('close', 'بسته شد')], default='waiting', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='فایل پیوست')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('Ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.Ticket')),
            ],
        ),
    ]
